name: CI Integration Tests
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      # Get local dependencies
      - run: yarn install
      - run: yarn build

      - run: 'echo "This is only for Integration tests on two blank projects"'

      - run: |
          mkdir danger_blank_test
          cd danger_blank_test
          yarn init --yes
          yarn add file:..
          echo "warn('I warned you')" > dangerfile.js
          echo "Testing a blank Dangerfile on an empty project"
          DEBUG="*" yarn danger run --text-only
          cd ..
          rm -rf danger_blank_test
        name: "Make a CRA"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          npm install -g create-react-app
          create-react-app danger_babel_test
          cd danger_babel_test
          yarn add file:..
          echo "warn('Expect 2 warnings'); const a = async () => {warn('the other');}; schedule(a)" > dangerfile.js
          echo "Testing a blank Dangerfile on a babel CRA project"
          DEBUG="*" yarn danger ci --text-only
          cd ..
          rm -rf danger_babel_test
        name: "Make a small babel app"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
